// ============================================================
// ICONS — single inline SVG line-icon set. Every glyph in the
// app (nav, categories, stats, achievements, toasts) resolves
// through icon(name) so there is one place to add/adjust icons.
// ============================================================

const PATHS = {
  home: '<path d="M4 11.5 12 4l8 7.5"/><path d="M6 10v9a1 1 0 0 0 1 1h4v-5h2v5h4a1 1 0 0 0 1-1v-9"/>',
  sword:
    '<line x1="5" y1="19" x2="19" y2="5"/><line x1="9.2" y1="11.2" x2="12.8" y2="14.8"/><circle cx="5" cy="19" r="1.3" fill="currentColor" stroke="none"/>',
  chart:
    '<rect x="4.5" y="13" width="3" height="7" rx="1" fill="currentColor" stroke="none"/><rect x="10.5" y="7" width="3" height="13" rx="1" fill="currentColor" stroke="none"/><rect x="16.5" y="10" width="3" height="10" rx="1" fill="currentColor" stroke="none"/>',
  star: '<polygon points="12,3 14.12,9.09 20.56,9.22 15.42,13.11 17.29,19.28 12,15.6 6.71,19.28 8.58,13.11 3.44,9.22 9.88,9.09" fill="currentColor" stroke="none"/>',
  user: '<circle cx="12" cy="8" r="3.5"/><path d="M5 20c0-3.5 3-6 7-6s7 2.5 7 6"/>',
  book: '<rect x="5" y="4" width="14" height="16" rx="1.5"/><line x1="9" y1="4" x2="9" y2="20"/>',
  dumbbell: '<line x1="6" y1="12" x2="18" y2="12"/><rect x="3" y="9" width="3" height="6" rx="1"/><rect x="18" y="9" width="3" height="6" rx="1"/>',
  heart:
    '<path d="M12 21c-4.2-3.6-8-6.9-8-10.8A4.6 4.6 0 0 1 8.6 5.6c1.4 0 2.7.7 3.4 1.8.7-1.1 2-1.8 3.4-1.8A4.6 4.6 0 0 1 20 10.2c0 3.9-3.8 7.2-8 10.8z" fill="currentColor" stroke="none"/>',
  palette:
    '<path d="M12 3a9 9 0 1 0 0 18c1.1 0 2-.9 2-2 0-.5-.2-1-.5-1.3-.3-.4-.5-.8-.5-1.2 0-.9.7-1.5 1.5-1.5H17a4 4 0 0 0 4-4c0-4.4-4-8-9-8z"/><circle cx="7.5" cy="10.5" r="1.2" fill="currentColor" stroke="none"/><circle cx="10.5" cy="7" r="1.2" fill="currentColor" stroke="none"/><circle cx="15" cy="7.5" r="1.2" fill="currentColor" stroke="none"/><circle cx="17" cy="11.5" r="1.2" fill="currentColor" stroke="none"/>',
  briefcase: '<rect x="3" y="8" width="18" height="12" rx="2"/><path d="M8 8V6a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/><line x1="3" y1="13" x2="21" y2="13"/>',
  sparkle: '<polygon points="12,3 14.97,9.03 21,12 14.97,14.97 12,21 9.03,14.97 3,12 9.03,9.03" fill="currentColor" stroke="none"/>',
  brain: '<circle cx="12" cy="12" r="8"/><path d="M8 9c1 1.5 1 3.5 0 5M12 8v8M16 9c-1 1.5-1 3.5 0 5"/>',
  coin: '<circle cx="12" cy="12" r="8.5"/><line x1="12" y1="7" x2="12" y2="17"/><path d="M9.5 9.5c0-1.1 1.1-2 2.5-2s2.5.7 2.5 1.7c0 2.3-5 1-5 3.3 0 1 1.1 1.8 2.5 1.8s2.5-.9 2.5-2"/>',
  users:
    '<circle cx="9" cy="9" r="3.2"/><path d="M3.5 19c0-3 2.5-5.2 5.5-5.2s5.5 2.2 5.5 5.2"/><circle cx="17" cy="10" r="2.6"/><path d="M15.5 13.2c2.6.3 4.5 2.3 4.5 5"/>',
  zap: '<polygon points="13,2 4,14 11,14 10,22 20,9 13,9" fill="currentColor" stroke="none"/>',
  flame:
    '<path d="M12 22c4.4 0 7-2.8 7-6.8 0-3-1.7-5-3-6.7.3 2-.4 3-1.3 3.6-.2-3-1.7-6-4.4-7.6.6 2.6-.3 4.6-2 6.4C6.7 12.4 5 14 5 16.3 5 20 8 22 12 22z" fill="currentColor" stroke="none"/>',
  flag: '<line x1="5" y1="3" x2="5" y2="21"/><path d="M5 4h11l-2.5 3.5L16 11H5"/>',
  clock: '<circle cx="12" cy="12" r="8.5"/><path d="M12 7.5V12l3.2 2"/>',
  footprints:
    '<ellipse cx="8" cy="16" rx="2.3" ry="3.4" transform="rotate(-15 8 16)" fill="currentColor" stroke="none"/><ellipse cx="16" cy="9" rx="2.3" ry="3.4" transform="rotate(15 16 9)" fill="currentColor" stroke="none"/>',
  crown: '<path d="M4 18h16l1-9-4.5 3L12 6l-4.5 6L3 9l1 9z"/><line x1="4" y1="21" x2="20" y2="21"/>',
  plus: '<line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/>',
  check: '<path d="M5 13l4 4L19 7"/>',
  alert: '<circle cx="12" cy="12" r="9"/><line x1="12" y1="7" x2="12" y2="13"/><circle cx="12" cy="16.5" r="0.9" fill="currentColor" stroke="none"/>',
};

export function icon(name, { size = 20, className = "" } = {}) {
  const inner = PATHS[name] || PATHS.sparkle;
  return `<svg class="icon${className ? " " + className : ""}" width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="square" stroke-linejoin="miter" aria-hidden="true">${inner}</svg>`;
}

// Fills every static [data-icon] placeholder in `root` once — used for
// markup that's already in index.html (nav bar, home stat tiles) rather
// than generated by a screen's render() function.
export function hydrateStaticIcons(root = document) {
  root.querySelectorAll("[data-icon]").forEach((el) => {
    const size = Number(el.dataset.iconSize) || 20;
    el.innerHTML = icon(el.dataset.icon, { size });
  });
}
